CREATE TABLE [stg].[Materials]
(
[MaterialID] [int] NULL,
[Jurisdiction] [int] NULL,
[MaterialDateReceived] [datetime] NULL,
[MaterialTitle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaterialDescription] [varchar] (1174) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaterialPhase] [int] NULL,
[MaterialStatus] [int] NULL,
[MaterialSource] [int] NULL,
[MaterialStaffReviewer] [int] NULL,
[MaterialNotes] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaterialReportingTool] [bit] NULL,
[MaterialFile] [varchar] (396) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaterialCommerceID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaterialTypeCFP] [bit] NULL,
[MaterialTypeCPP] [bit] NULL,
[MaterialTypeEconomicDevelopment] [bit] NULL,
[MaterialTypeFLUM] [bit] NULL,
[MaterialTypeFunctionalPlan] [bit] NULL,
[MaterialTypeFunctionalPlanSpecify] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaterialTypeHousing] [bit] NULL,
[MaterialTypeLandUse] [bit] NULL,
[MaterialTypeMinorAmendments] [bit] NULL,
[MaterialTypeOther] [bit] NULL,
[MaterialTypeOtherSpecify] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaterialTypeParks] [bit] NULL,
[MaterialTypePeriodicUpdate] [bit] NULL,
[MaterialTypeRegionalCenter] [bit] NULL,
[MaterialTypeRural] [bit] NULL,
[MaterialTypeScopingNotice] [bit] NULL,
[MaterialTypeSMP] [bit] NULL,
[MaterialTypeSubareaPlan] [bit] NULL,
[MaterialTypeTransportation] [bit] NULL,
[MaterialTypeUGAChange] [bit] NULL,
[MaterialTypeUtilities] [bit] NULL,
[DateAdded] [datetime] NULL
) ON [PRIMARY]
GO
